@extends('front.layout.app')

@section('title')
    <title>{{trans('web.title.home')}} | {{trans('web.title.welcome_to_qasr_al_mahba')}}</title>
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('css/contact_us.css?v=1.3')}}">
    <link rel="stylesheet" href="{{asset('vendors/quill/quill.snow.css')}}">
@endsection
@section('content')
    <div class="page-wrapper">
    @include('front.layout.header')
        <div class="homepage-banner">
            @foreach($banners as $banner)
                <section class="hero-section overlay" style="background: url({{$banner->image}}); background-size: cover;">
                    <div class="container">
                        <div class="hero-inner">
                            <h1>
                                <span class="wow fadeInUp" data-wow-duration="1s"
                                      data-wow-delay="0.3s">{{$banner->title}}</span><br>
                            </h1>
                            <a href="{{route('contact')}}" class="theme-btn wow fadeInUp" data-wow-duration="1s"
                               data-wow-delay="1s">
                                {{trans('web.home.banner.contact_us')}} <i class="fas fa-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </section>
            @endforeach
        </div>
        <div class="our-success pb-30 rpb-0 wow fadeInUp" data-wow-duration="2s">
            <div class="container">
                <div class="success-wrap bg-blue">
                    <div class="row">
                        <div class="col-xl-4 col-lg-4 col-md-4">
                            <div class="success-item">
                                <div class="success-content">
                                    <span class="count-text">{{trans('web.home.mining_license_title')}}</span>
                                    <p>{{trans('web.home.mining_license_content')}}</p>
                                </div>
                            </div>
                            <a href="{{route('mining-license')}}" class="theme-btn wow fadeInUp" data-wow-duration="1s"
                               data-wow-delay="1s">
                                {{trans('web.home.read_more')}} <i class="fas fa-arrow-right"></i>
                            </a>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-4">
                            <div class="success-item">
                                <div class="success-content">
                                    <span class="count-text">{{trans('web.home.mining_process_title')}}</span>
                                    <p>{{trans('web.home.mining_process_content')}}</p>
                                </div>
                            </div>
                            <a href="{{route('mining-process')}}" class="theme-btn wow fadeInUp" data-wow-duration="1s"
                               data-wow-delay="1s">
                                {{trans('web.home.read_more')}} <i class="fas fa-arrow-right"></i>
                            </a>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-4">
                            <div class="success-item">
                                <div class="success-content">
                                    <span class="count-text">{{trans('web.home.new_product_title')}}</span>
                                    <p>{{trans('web.home.new_product_content')}}</p>
                                </div>
                            </div>
                            <a href="javascript:void" class="theme-btn wow fadeInUp" data-wow-duration="1s"
                               data-wow-delay="1s">
                                {{trans('web.home.read_more')}} <i class="fas fa-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <section class="video-section bg-snow pt-140 rpt-90 pb-110 rpb-60">
            <div class="container">
                <div class="row">
                    @if(count($links))
                        <div id="player" class="col-lg-6 col-sm-12">
                            <div class="player">
                                <div class="player__video">
                                    <!-- Current video is for reference only. It will be generated by JavaScript code. -->
                                    <iframe id="current-video" class="current-video" width="560" height="315"
                                            src="https://www.youtube.com/embed/{{$links->first()->link}}" frameborder="0"
                                            allow="autoplay; encrypted-media" allowfullscreen></iframe>
                                </div>
                            </div>
                        </div>
                        <div id="gallery" class="col-lg-6 col-sm-12">
                            <div class="gallery"></div>
                        </div>
                    @endif
                </div>
            </div>
        </section>
    @include('front.partners')
        <section class="investing-section pt-135 rpt-85 pb-145 rpb-130">
            <div class="container" style="position: relative">
                <div class="row">
                    <img src="{{asset('images/invest_map.jpg')}}">
                    <div class="col-6">

                    </div>
                    <div class="col-6 invest-text">
                        <div id="textbox">
                            <h2>{{trans('web.home.invest_in_mozambique_title')}}</h2>
                            <p>
                                {{trans('web.home.invest_in_mozambique_description')}}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="investing-section pt-135 rpt-85 pb-145 rpb-130">
            <div class="container" style="position: relative">
                <h2 class="text-center">{{trans('web.home.articles')}}</h2>
            @foreach($articles as $article)
                <div class="row">
                    <div class="col-12 pl-30 pr-30">
                        <h3>{{$article->title}}</h3>
                        <div class="ql-editor">
                            {!! $article->content !!}
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </section>
        <section class="zero-padding-contact-us mb-100">
            <div class="container">
                <h4 class="mb-75 text-sm-center">{{trans('web.home.contact_us_title')}}</h4>
                @include('front.contact_us_form')
            </div>
        </section>
    </div>
    @include('front.layout.footer')
@endsection
<!--End pagewrapper-->
@section('js')
    <script>

        const links = JSON.parse(`@json($links)`);
        let arrVideos = [];
        const ytVideoPrefix = `https://www.youtube.com/embed/`
        const ytImagePathPrefix = `https://i.ytimg.com/vi/`
        const ytImagePathSufix = `/maxresdefault.jpg`

        for (var i = 0; i < links.length; i++) {
            arrVideos.push({data: links[i].link});
        }
        let currentVideo = document.getElementById('current-video')
        currentVideo.src = `${ytVideoPrefix}${arrVideos[0].data}`


        let gallery = document.querySelector('.gallery')
        gallery.innerHTML = ``

        for (let i = 0; i < arrVideos.length; i++) {
            gallery.innerHTML += `
            <div class="gallery__item filtered"
            style="background-image: url(${ytImagePathPrefix}${arrVideos[i].data}${ytImagePathSufix})"
            data="${arrVideos[i].data}">
            </div>`
        }

        gallery.addEventListener('click', (e) => {
            // When click on .gallery__item element
            if (e.target.classList.contains('gallery__item')) {
                currentVideo.src = `${ytVideoPrefix}${e.target.getAttribute('data')}`
            }
            // When click on .gallery__item__img element
            if (e.target.classList.contains('gallery__item__img')) {
                let data = e.target.src
                data = data.replace(ytImagePathPrefix, '')
                data = data.replace(ytImagePathSufix, '')
                currentVideo.src = `${ytVideoPrefix}${data}`
                console.log(currentVideo.src)
            }
            // When click on .gallery__item__span element
            if (e.target.classList.contains('gallery__item__span')) {
                console.log(e.target.innerText)
                for (let i = 0; i < arrVideos.length; i++) {
                    if (arrVideos[i].name === e.target.innerText) {
                        currentVideo.src = `${ytVideoPrefix}${arrVideos[i].data}`
                    }
                }
            }
        });
    </script>
@endsection
