<section class="video-section bg-snow pt-50 mb-50 rpt-50 pb-50 rpb-60">
    <div class="container">
        <div class="row">
            @if(count($links))
                <div id="player" class="col-lg-6 col-sm-12">
                    <div class="player">
                        <div class="player__video">
                            <!-- Current video is for reference only. It will be generated by JavaScript code. -->
                            <iframe id="current-video" class="current-video" width="560" height="315"
                                    src="https://www.youtube.com/embed/{{$links->first()->link}}" frameborder="0"
                                    allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
                <div id="gallery" class="col-lg-6 col-sm-12">
                    <div class="gallery"></div>
                </div>
            @endif
        </div>
    </div>
</section>
